### ISSUE TITLE
mysterious text_score on 1 character difference

### ISSUE THREAD

**Issue by andrasvereckei** [ceumicrodata/firm_name_search#1]
We don't understand the text_score in this case: 

name: `CREDICET Fejlesztési Zárkörűen Működő Részvénytársaság`
found_name: `CREDICET Fejlesztési Zártkörűen Működő Részvénytársaság`
tax_id: `11108937`
org_score: `2`
text_score: `.7017544`

**Comment by korenmiklos** [comment]
typo: zárkörűen
